Adds initial version bump stage

diff --git a/.github/workflows/release_branch.yml b/.github/workflows/release_branch.yml
--- a/.github/workflows/release_branch.yml
+++ b/.github/workflows/release_branch.yml
@@ -81,57 +81,92 @@ jobs:
 
 # Checks if documentation/documentation_mapping.json exists and runs tools
 # to generate README markdown and metadata file if so.
-  generate_readme_metadata:
+  # generate_readme_metadata:
+  #   runs-on: ubuntu-latest
+  #   # needs:
+  #   #   - documentation_validation
+  #   #   - schema_validation
+  #   #   - schemaLinks_validation
+  #   if: "!contains(github.event.head_commit.message, 'Skip CI')"
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Generates README and metadata files
+  #       env:
+  #         NPMRC_TOKEN: ${{ secrets.NPMRC_TOKEN }}
+  #         ARGO_NPMRC_TOKEN: ${{ secrets.ARGO_NPMRC_TOKEN }}
+  #         GENERATE_READMES: ${{ vars.GENERATE_READMES }}
+  #       # Runs generate readme scripts for asset readmes
+  #       run: |
+  #         wget https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/node_setup.sh
+  #         bash ./node_setup.sh
+  #         if [ -e "documentation/documentation_mapping.json" ]; then
+  #           mkdir -p readmeUtils
+  #           mkdir -p tabUtils
+  #           wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_readme_utils.py
+  #           wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_readme.jinja2
+  #           wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_readme.py
+  #           wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_readme.sh
+  #           wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_asset_readmes.jinja2
+  #           wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_asset_readmes.py
+  #           wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/map_asset_values.py
+  #           wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_metadata.py
+  #           wget -q -P ./tabUtils https://gitlab.com/itentialopensource/opensource-common-utils/-/raw/master/documentation-pipeline-tool.js
+  #           wget -q -P ./tabUtils https://gitlab.com/itentialopensource/opensource-common-utils/-/raw/master/projectTypeTemplates/project-templates.md
+  #           chmod +x tabUtils/documentation-pipeline-tool.js
+  #           echo "Running readme generation"
+  #           bash ./readmeUtils/generate_readme.sh
+  #           echo "GENERATE_READMES: $GENERATE_READMES"
+  #           echo "Running TAB1 and TAB2 generation... -p '.' -u $GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
+  #           node ./tabUtils/documentation-pipeline-tool.js -p "." -u "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
+  #         else
+  #           echo "Skipping readme generation. Adding required documentation will remove this error."
+  #           echo "Exiting job with a warning"
+  #           if [[ "$GENERATE_READMES" == "true" ]]; then
+  #             exit 1
+  #           fi
+  #         fi
+  #     - name: Upload generated markdown and metadata files
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: readme_metadata_artifacts
+  #         path: |
+  #           README.md
+  #           documentation/
+  #           metadata.json
+  #           TAB1.md
+  #           TAB2.md
+
+# Bumps the version of package/package-lock and generates a new artifact.json
+  version_bump:
     runs-on: ubuntu-latest
-    # needs:
-    #   - documentation_validation
-    #   - schema_validation
-    #   - schemaLinks_validation
     if: "!contains(github.event.head_commit.message, 'Skip CI')"
     steps:
       - uses: actions/checkout@v4
-      - name: Generates README and metadata files
+      - name: Bumps Pre-Built version and generates new artifact.json
         env:
           NPMRC_TOKEN: ${{ secrets.NPMRC_TOKEN }}
           ARGO_NPMRC_TOKEN: ${{ secrets.ARGO_NPMRC_TOKEN }}
           GENERATE_READMES: ${{ vars.GENERATE_READMES }}
-        # Runs generate readme scripts for asset readmes
         run: |
+          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
+          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
+          echo "GITHUB_REF: $GITHUB_REF"
+          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
+          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
+
           wget https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/node_setup.sh
           bash ./node_setup.sh
-          if [ -e "documentation/documentation_mapping.json" ]; then
-            mkdir -p readmeUtils
-            mkdir -p tabUtils
-            wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_readme_utils.py
-            wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_readme.jinja2
-            wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_readme.py
-            wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_readme.sh
-            wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_asset_readmes.jinja2
-            wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_asset_readmes.py
-            wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/map_asset_values.py
-            wget -q -P ./readmeUtils https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/readmeUtils/generate_metadata.py
-            wget -q -P ./tabUtils https://gitlab.com/itentialopensource/opensource-common-utils/-/raw/master/documentation-pipeline-tool.js
-            wget -q -P ./tabUtils https://gitlab.com/itentialopensource/opensource-common-utils/-/raw/master/projectTypeTemplates/project-templates.md
-            chmod +x tabUtils/documentation-pipeline-tool.js
-            echo "Running readme generation"
-            bash ./readmeUtils/generate_readme.sh
-            echo "GENERATE_READMES: $GENERATE_READMES"
-            echo "Running TAB1 and TAB2 generation... -p '.' -u $GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
-            node ./tabUtils/documentation-pipeline-tool.js -p "." -u "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
-          else
-            echo "Skipping readme generation. Adding required documentation will remove this error."
-            echo "Exiting job with a warning"
-            if [[ "$GENERATE_READMES" == "true" ]]; then
-              exit 1
-            fi
-          fi
-      - name: Upload generated markdown and metadata files
-        uses: actions/upload-artifact@v4
-        with:
-          name: readme_metadata_artifacts
-          path: |
-            README.md
-            documentation/
-            metadata.json
-            TAB1.md
-            TAB2.md
+          # # Bumps node version without creating commiting new tag repo. Adds IAP version tagging if branch is Master or release.
+          # # This conditional is seperated into two parts instead of one script because of current errors in ci/cd regex
+          # if [[ "$GITHUB_HEAD_REF" =~ release/ || "$GITHUB_REF_NAME" =~ release/ ]]; then
+          #   wget https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/version_bump_release.sh
+          #   chmod +x version_bump_release.sh
+          #   ./version_bump_release.sh $GENERATE_READMES
+          # else
+          #   wget https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/version_bump_master.sh
+          #   chmod +x version_bump_master.sh
+          #   ./version_bump_master.sh $GENERATE_READMES
+          # fi
+          # wget https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/generate.js
+          # chmod +x generate.js
+          # node generate "$GITHUB_RUN_ID" "$GITHUB_REPOSITORY" "$GITHUB_REF"
